jwt:
  secret: "ig@RBack010end#"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://postgres/backend
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8080